version: "3"

services:
  postgres-db-iluvcoffee:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iluvcoffee
    ports:
      - "54321:5432"
  test-postgres-db-iluvcoffee:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iluvcoffee
    ports:
      - "54322:5432"
